# Generated by Django 5.2.1 on 2025-05-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20250511_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='button_text',
            field=models.CharField(blank=True, default='Подробнее', max_length=50, verbose_name='Текст кнопки'),
        ),
    ]
